package com.durelljardim.kitabu.ui.theme

import androidx.compose.ui.graphics.Color

val InkBlue = Color(0xFF1F3A5F)
val InkBlueSoft = Color(0xFFDCE4EE)
val PaperWhite = Color(0xFFFFFFFF)
val Paper = Color(0xFFFAF8F4)
val InkText = Color(0xFF1C1B19)
val PaperDark = Color(0xFFECE8E1)
val MutedText = Color(0xFF6B6862)
val Hairline = Color(0xFFCFCAC0)
val HairlineLight = Color(0xFFE4E0D8)
val ContainerLowest = Color(0xFFFFFFFF)
val ContainerLow = Color(0xFFF5F2EC)
val Container = Color(0xFFF0EDE6)
val ContainerHigh = Color(0xFFEAE6DF)

val InkBlueDark = Color(0xFFA9C1E0)
val InkBlueOnDark = Color(0xFF0E2238)
val InkBlueContainerDark = Color(0xFF2A4467)
val NightPaper = Color(0xFF151412)
val NightText = Color(0xFFECE8E1)
val NightPaperDark = Color(0xFF2A2825)
val MutedTextDark = Color(0xFFA8A39A)
val HairlineDark = Color(0xFF4A4740)
val HairlineLightDark = Color(0xFF34322E)
val ContainerLowestDark = Color(0xFF100F0E)
val ContainerLowDark = Color(0xFF1C1B19)
val ContainerDark = Color(0xFF201F1C)
val ContainerHighDark = Color(0xFF2A2825)

// The status badges keep their own colours so they stay green and orange in both themes.
val AvailableText = Color(0xFF1E6B3F)
val AvailableBackground = Color(0xFFE4F1E8)
val BorrowedText = Color(0xFFA34A0B)
val BorrowedBackground = Color(0xFFFBE9DC)
val AvailableTextDark = Color(0xFF9FD6B0)
val AvailableBackgroundDark = Color(0xFF1F3A2A)
val BorrowedTextDark = Color(0xFFF2B98A)
val BorrowedBackgroundDark = Color(0xFF43291A)
